
const $=id=>document.getElementById(id),money=n=>Number(n||0).toLocaleString('ru-RU').replace(/\u00a0/g,' ');
let data=null,packs={},workReadyAt=0,currentDrop=null,selectedUpgrade=null,farmData=null,marketData=null;
function tgHeaders(){return {'Content-Type':'application/json','X-Telegram-Init-Data':window.Telegram?.WebApp?.initData||''};}
async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{...tgHeaders(),...(opt.headers||{})}});let j={};try{j=await r.json()}catch{}if(!r.ok)throw j;return j;}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(window.tt);window.tt=setTimeout(()=>$('toast').style.display='none',2600)}
function go(page){document.querySelectorAll('main section').forEach(s=>s.hidden=s.id!==page);document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='inventory')loadInventory();if(page==='profile'){loadProfile();loadRating()}if(page==='earn')loadTasks();if(page==='farm')loadFarm();if(page==='upgrade')loadUpgradeItems();if(page==='market')loadMarket();if(page==='world'){loadCollections();loadFarm();}window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));
function render(){const s=data.stats;$('bal').textContent=money(s.balance);$('level').textContent=s.level;$('xp').textContent=money(s.xp);$('packs').textContent=s.packs;$('items').textContent=s.items;$('streak').textContent='🔥 '+s.streak;const se=s.season;$('season').innerHTML=`<div class="season-line"><div><div class="season-name">${se.name}</div><div class="season-level">Сезонный уровень ${se.level}</div></div><span class="pill">${se.level}/${se.max_level}</span></div><div class="progress"><i style="width:${Math.min(100,se.progress/se.need*100)}%"></i></div><div class="muted">${se.progress} / ${se.need} XP до следующего уровня</div>`;renderPacks();renderTasks(data.tasks||[])}
function rarityClass(r){return r==='Обычный'?'rarity-common':r==='Редкий'?'rarity-rare':r==='Эпический'?'rarity-epic':r==='Легендарный'?'rarity-legendary':'rarity-mythic'}
function caseIcon(theme){return theme==='legend'?'♛':theme==='collab'?'✦':theme==='epic'?'◆':'✹'}
function renderPacks(){const el=$('packList');el.innerHTML='';Object.entries(packs).forEach(([key,p],idx)=>{const items=(p.items||[]).slice().sort((a,b)=>b.value-a.value);const best=items[0];const d=document.createElement('div');d.className=`pack case-pack case-theme-${p.theme||'starter'}`;d.innerHTML=`<div class="case-glow"></div><span class="case-badge theme">${idx===0?'СТАРТ':best.rarity.toUpperCase()}</span><div class="pack-top"><div><div class="case-rarity ${rarityClass(best.rarity)}">${p.name}</div><b style="font-size:20px">${p.name}</b><div class="muted">${p.subtitle||'Особый кейс SHAMA WORLD'}</div><div class="muted" style="margin-top:4px">⭐ +${p.xp} XP · ${items.length} предметов</div></div><div class="price">${money(p.price)} SH</div></div><div class="case-art"><span>${caseIcon(p.theme)}</span><div class="case-theme-label">${(p.theme||'starter').toUpperCase()} DROP SERIES</div></div><div class="pack-items">${items.map(x=>`<span class="pack-item"><span class="${rarityClass(x.rarity)}">${x.emoji} ${x.name}</span><br><small>${x.rarity} · ${x.chance}% · ${money(x.value)} SH</small></span>`).join('')} ${(p.coin_drops||[]).map(x=>`<span class="pack-item coin-drop">💠 ${money(x.amount)} SH · ${x.chance}%</span>`).join('')}</div><button class="primary" style="margin-top:12px">🎰 ОТКРЫТЬ КЕЙС</button>`;d.querySelector('button').onclick=()=>openPack(key);el.appendChild(d)})}

function renderTasks(list){const daily=list.filter(t=>t.key!=='weekly');$('tasks').innerHTML=daily.map(t=>`<div class="task"><div class="task-head"><div><b>${t.title}</b><div class="muted">${t.description}</div></div><div class="reward">+${money(t.reward)} SH</div></div><div class="progress"><i style="width:${Math.min(100,(t.progress||0)/(t.target||1)*100)}%"></i></div><div class="taskbar"><span class="mini">${Math.min(t.progress||0,t.target||1)} / ${t.target||1} · +${t.xp} XP</span><button class="ghost" ${t.claimed||!t.ready?'disabled':''}>${t.claimed?'ЗАБРАНО':t.ready?'ЗАБРАТЬ':'В ПРОЦЕССЕ'}</button></div></div>`).join('');daily.forEach((t,i)=>{const b=$('tasks').children[i]?.querySelector('button');if(b&&!b.disabled)b.onclick=()=>claimTask(t.key)});const w=list.find(x=>x.key==='weekly');if(w)$('weekly').innerHTML=`<div class="task-head"><div><b>${w.title}</b><div class="muted">${w.description}</div></div><b class="reward">+${money(w.reward)} SH</b></div><div class="progress"><i style="width:${(w.progress||0)/w.target*100}%"></i></div><div class="taskbar"><span class="mini">${w.progress||0} / ${w.target}</span><button class="ghost" ${w.ready?'':'disabled'} onclick="claimTask('weekly')">${w.claimed?'ЗАБРАНО':w.ready?'ЗАБРАТЬ':'В ПРОЦЕССЕ'}</button></div>`}
async function load(){try{data=await api('/api/me');packs=data.packs;render();}catch(e){toast('Открой Mini App через Telegram')}}
async function loadTasks(){try{const j=await api('/api/tasks');data.tasks=j.items;renderTasks(j.items)}catch(e){toast('Не удалось загрузить задания')}}
async function bonus(){try{const j=await api('/api/bonus',{method:'POST'});toast(`🎉 +${money(j.reward)} SH · серия ${j.streak}`);await load()}catch(e){toast(e.reason==='already'?'🎁 Бонус уже получен сегодня':'Ошибка бонуса')}}
async function work(){try{const j=await api('/api/work',{method:'POST'});toast(`⚡ +${money(j.reward)} SH`);workReadyAt=Date.now()+j.cooldown*1000;updateWorkTimer();await load()}catch(e){if(e.reason==='cooldown'){workReadyAt=Date.now()+e.remaining*1000;updateWorkTimer();toast('⚡ Активность пока на перезарядке')}else toast('Не удалось получить награду')}}
function updateWorkTimer(){const el=$('workTimer2');if(!el)return;const tick=()=>{const sec=Math.max(0,Math.ceil((workReadyAt-Date.now())/1000));if(sec<=0){el.textContent='Готово';return}const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;el.textContent=`Следующая награда через ${h?String(h).padStart(2,'0')+':':''}${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;setTimeout(tick,1000)};tick()}
async function claimTask(key){try{const j=await api('/api/claim-task',{method:'POST',body:JSON.stringify({task:key})});toast(`🎯 +${money(j.reward)} SH`);await load()}catch(e){toast(e.reason==='already'?'Уже забрано':e.reason==='not_ready'?'Задание ещё не выполнено':'Ошибка задания')}}
function rarityClass(r){const m={'Обычный':'rarity-common','Редкий':'rarity-rare','Эпический':'rarity-epic','Легендарный':'rarity-legendary','Мифический':'rarity-mythic','Монеты':'rarity-legendary'};return m[r]||'rarity-common'}
function rouletteItems(p,drop){const all=p.items||[];const base=[];for(let i=0;i<24;i++){const x=all[Math.floor(Math.random()*all.length)];base.push(x)}const center=19;base[center]=drop.kind==='item'?drop:{name:drop.name,emoji:'💠',rarity:'Монеты',value:drop.value};return base}
function drawRoulette(items,animate=true){const track=$('rouletteTrack');track.innerHTML=items.map((x,i)=>`<div class="roll-item ${rarityClass(x.rarity)}" data-index="${i}"><div class="emoji">${x.emoji}</div><b>${x.name}</b><small>${money(x.value||0)} SH</small></div>`).join('');track.classList.remove('spinning');track.style.transition='none';track.style.transform='translateX(0)';void track.offsetWidth;if(animate){track.classList.add('spinning');const itemWidth=120;const center=19;const viewport=window.innerWidth<390?49:56;const offset=(center*itemWidth)-viewport;track.style.transition='transform 4.2s cubic-bezier(.08,.74,.09,1)';track.style.transform=`translateX(${-offset}px)`}}
function sound(type){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=window.__audio||(window.__audio=new C());const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=type==='win'?720:type==='rare'?520:260;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.045,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+(type==='win'?0.42:.09));o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+(type==='win'?0.45:.1))}catch(e){}}
function confetti(rarity){const box=$('confetti');box.innerHTML='';const n=rarity==='Мифический'?80:rarity==='Легендарный'?55:rarity==='Эпический'?35:18;for(let i=0;i<n;i++){const e=document.createElement('i');e.style.left=Math.random()*100+'%';e.style.setProperty('--x',(Math.random()*260-130)+'px');e.style.animationDelay=(Math.random()*.35)+'s';e.style.transform=`rotate(${Math.random()*180}deg)`;box.appendChild(e)}setTimeout(()=>box.innerHTML='',2200)}
function rarityEffect(rarity){return rarity==='Мифический'?'mythic':rarity==='Легендарный'?'legendary':rarity==='Эпический'?'epic':rarity==='Редкий'?'rare':''}
let openingKey=null,openingTimer=null;
async function openPack(key){openingKey=key;go('opening');$('dropActions').hidden=true;$('afterCaseActions').hidden=true;$('reveal').className='reveal';$('openText').textContent='Проверяем баланс и запускаем прокрутку…';$('openStage').textContent='ПРОВЕРКА';$('openChance').textContent='SERVER DROP';$('spinProgress').style.width='4%';$('rouletteWindow').classList.remove('hot');$('jackpotBadge').classList.remove('hot');const p=packs[key];$('caseTitle').textContent=p.name;$('case').className=`case case-themed case-theme-${p.theme||'starter'}`;$('rouletteWindow').className=`roulette-window theme-window`;$('caseFlash').classList.remove('flash');sound('start');try{const j=await api('/api/open-pack',{method:'POST',body:JSON.stringify({pack:key})});currentDrop=j.drop;const items=rouletteItems(p,j.drop);drawRoulette(items,true);$('openStage').textContent='ПРОКРУТКА';$('openChance').textContent=j.drop.kind==='coin'?'SH DROP':'DROP LOCKED';$('spinStatus').innerHTML='Ищем победный дроп…<span class="spin-dots"><i></i><i></i><i></i></span>';$('openText').textContent='Не закрывай окно — рулетка выбирает победителя';$('rouletteWindow').classList.add('hot');let started=Date.now();clearInterval(openingTimer);openingTimer=setInterval(()=>{const pct=Math.min(96,4+((Date.now()-started)/4200)*92);$('spinProgress').style.width=pct+'%'},80);setTimeout(()=>{clearInterval(openingTimer);$('spinProgress').style.width='100%';const winner=$('rouletteTrack').querySelector('[data-index="19"]');if(winner)winner.classList.add('winner');showDrop(j.drop);},4400)}catch(e){clearInterval(openingTimer);go('packs');toast(e.reason==='money'?`Не хватает ${money(e.need)} SH`:'Не удалось открыть кейс')}}
function showDrop(drop){const effect=rarityEffect(drop.rarity);$('caseFlash').classList.remove('flash');void $('caseFlash').offsetWidth;$('caseFlash').classList.add('flash');$('dropEmoji').textContent=drop.emoji;$('dropRarity').textContent=drop.rarity;$('dropRarity').className='rarity '+effect;$('dropName').textContent=drop.name;$('dropValue').textContent=drop.kind==='coin'?`+${money(drop.value)} SH`:`${money(drop.value)} SH · шанс ${drop.chance}%`;$('dropSub').textContent=drop.kind==='coin'?'SH уже зачислены на баланс.':(drop.rarity==='Мифический'?'Невероятная находка. Предмет уже в коллекции.':'Предмет уже добавлен в коллекцию.');$('reveal').className='reveal show '+effect;$('dropActions').hidden=false;$('afterCaseActions').hidden=false;$('spinStatus').textContent='ВЫПАЛО';$('openStage').textContent=drop.rarity==='Мифический'?'МИФИЧЕСКИЙ ДРОП':drop.rarity.toUpperCase();$('openChance').textContent=drop.kind==='coin'?'SH BONUS':`${drop.chance}% CHANCE`;$('upgradeDropBtn').style.display=drop.kind==='item'?'block':'none';$('openText').textContent=drop.kind==='coin'?'💠 Бонус SH уже на балансе':'🎒 Предмет сохранён автоматически';sound(drop.rarity==='Мифический'||drop.rarity==='Легендарный'?'win':drop.rarity==='Эпический'||drop.rarity==='Редкий'?'rare':'start');confetti(drop.rarity);if(drop.rarity==='Мифический'||drop.rarity==='Легендарный')$('jackpotBadge').classList.add('hot');setTimeout(()=>load(),250)}
function saveDrop(){if(!currentDrop)return;if(currentDrop.kind==='coin'){toast('💠 Монеты уже зачислены');return}toast('🎒 Предмет сохранён в коллекции');go('inventory')}
function upgradeFromDrop(){if(!currentDrop||currentDrop.kind!=='item')return;go('upgrade');selectUpgrade(currentDrop.name)}
function openSameCase(){if(openingKey)openPack(openingKey)}
async function loadInventory(){try{const j=await api('/api/inventory');$('inv').innerHTML=j.items.length?j.items.map(x=>`<div class="row card" style="padding:14px;margin-bottom:10px"><div><b>${x.emoji} ${x.name}</b><div class="muted">${x.rarity} · ${money(x.value)} SH · ×${x.quantity}</div></div><button class="ghost" onclick="selectUpgrade('${String(x.name).replaceAll("'","\\'")}')">АПГРЕЙД</button></div>`).join(''):'<div class="card empty">Пока пусто.<br><span class="muted">Заработай SH и открой первый кейс.</span></div>';const h=await api('/api/history');$('history').innerHTML=h.items.map(x=>`<div class="history ${x.amount>=0?'positive':'negative'}"><div class="row"><b>${x.emoji} ${x.title}</b><b class="${x.amount>=0?'reward':''}">${x.amount>0?'+':''}${money(x.amount)} SH</b></div><div class="muted">Баланс: ${money(x.balance_after)} SH · ${x.created_at}</div></div>`).join('')}catch(e){toast('Не удалось загрузить коллекцию')}}
async function loadUpgradeItems(){try{const j=await api('/api/inventory');$('upgradeItems').innerHTML=j.items.length?j.items.map(x=>`<div class="row upgrade-card"><div><b>${x.emoji} ${x.name}</b><div class="muted">${x.rarity} · ${money(x.value)} SH · ×${x.quantity}</div></div><button class="ghost" onclick="selectUpgrade('${String(x.name).replaceAll("'","\\'")}')">ВЫБРАТЬ</button></div>`).join(''):'<div class="card empty">В инвентаре пока нет предметов.</div>'}catch(e){toast('Не удалось загрузить предметы')}}
async function selectUpgrade(name){go('upgrade');selectedUpgrade=name;try{const j=await api('/api/upgrade-options?item='+encodeURIComponent(name));const s=j.source;$('upgradeSource').innerHTML=`<div class="source-box"><div class="source-main"><div class="source-emoji">${s.emoji}</div><div><b>${s.name}</b><div class="muted">${s.rarity} · ${money(s.value)} SH · ×${s.quantity}</div></div></div><div class="section" style="margin-top:12px"><div class="muted">Выбери цель</div></div><div class="target-grid">${j.targets.length?j.targets.map(t=>`<div class="target"><div class="target-left"><div class="target-icon">${t.emoji}</div><div><b>${t.name}</b><div class="muted">${t.rarity} · ${money(t.value)} SH</div></div></div><div style="text-align:right"><div class="chance">${t.chance}%</div><button class="ghost" style="margin-top:5px;padding:8px 10px" onclick="doUpgrade('${String(s.name).replaceAll("'","\\'\'\'\'")}','${String(t.name).replaceAll("'","\\'\'\'\'")}')">УЛУЧШИТЬ</button></div></div>`).join(''):'<div class="empty muted">Для этого предмета пока нет более дорогой цели.</div>'}</div></div>`}catch(e){$('upgradeSource').innerHTML='<div class="card empty">Не удалось загрузить варианты апгрейда.</div>'}}
async function doUpgrade(source,target){try{const j=await api('/api/upgrade',{method:'POST',body:JSON.stringify({source,target})});if(j.success){toast(`🎉 Успех! ${j.target} · ${money(j.target_value)} SH`)}else{toast(`Неудача. Шанс был ${j.chance}% — предмет сгорел`)}selectedUpgrade=null;await load();await loadUpgradeItems();}catch(e){toast(e.reason==='item'?'Предмет больше недоступен':e.reason==='target'?'Неверная цель':'Апгрейд не выполнен')}}
async function loadFarm(){try{const j=await api('/api/farm');farmData=j;$('farmPending').textContent=money(j.total_pending)+' SH';$('farmList').innerHTML=j.farms.map((f,i)=>{const locked=!f.unlocked;const max=f.level>=f.max_level;const isBank=f.key==='bank';const middle=locked?`<div class="mini">🔒 Сначала полностью прокачай ${j.farms[i-1]?.name||'предыдущий объект'}</div>`:(!isBank?`<div class="farm-total"><div><div class="muted">Накоплено</div><b>${money(f.pending)} SH</b></div><span class="pill">${f.milestone||'Развитие'}</span></div>`:'');const bottom=isBank?`<div class="bank-stat"><div><span class="muted">Хранилище</span><b>${money(f.storage)} SH</b></div><div><span class="muted">Комиссия рынка</span><b>${f.fee}%</b></div></div>`:`<div class="farm-milestone">🏗️ ${f.milestone||''} · после уровня: ${f.next_income!==null?money(f.next_income)+' SH/мин':'MAX'}</div>`;const actions=locked?'':`<div class="farm-actions"><button class="ghost" onclick="collectFarm()">ЗАБРАТЬ ${f.pending?money(f.pending)+' SH':''}</button><button class="primary" ${max?'disabled':''} onclick="upgradeFarm('${f.key}')">${max?'МАКСИМУМ':'⬆️ УЛУЧШИТЬ · '+money(f.next_cost)+' SH'}</button></div>`;return `<div class="farm-card ${locked?'locked':''}"><div class="farm-head"><div style="display:flex;align-items:center;gap:11px"><div class="farm-icon">${f.icon}</div><div><div class="farm-name">${f.name}</div><div class="farm-level">УРОВЕНЬ ${f.level} / ${f.max_level}</div></div></div><div class="income">${isBank?'—':money(f.income)}<small>${isBank?'экономика':' SH/мин'}</small></div></div><p class="muted">${f.description}</p><div class="progress"><i style="width:${f.level/f.max_level*100}%"></i></div>${middle}${actions}${bottom}</div>`}).join('')}catch(e){toast('Не удалось загрузить ферму')}}
async function collectFarm(){try{const j=await api('/api/farm/collect',{method:'POST'});toast(`🌾 +${money(j.reward)} SH`);await load();await loadFarm()}catch(e){toast(e.reason==='empty'?'Пока нечего собирать':'Не удалось собрать доход')}}
async function upgradeFarm(key){try{const j=await api('/api/farm/upgrade',{method:'POST',body:JSON.stringify({farm:key})});toast(`⬆️ Уровень ${j.level} · ${money(j.income)} SH/мин`);await load();await loadFarm()}catch(e){toast(e.reason==='money'?`Не хватает ${money(e.need)} SH`:e.reason==='locked'?'Сначала полностью прокачай предыдущий бизнес':'Не удалось улучшить')}}
async function loadMarket(){try{marketData=await api('/api/market');renderMarket();renderMyListings()}catch(e){toast('Не удалось загрузить рынок')}}
function renderMarket(){if(!marketData)return;const q=($('marketSearch')?.value||'').toLowerCase();const list=(marketData.items||[]).filter(x=>x.item_name.toLowerCase().includes(q));$('marketList').innerHTML=list.length?list.map(x=>`<div class="market-card"><div class="row"><div><b>${x.emoji} ${x.item_name}</b><div class="market-meta">${x.rarity} · ${money(x.value)} SH · ×${x.quantity}</div><div class="market-meta">Продавец: ${x.first_name||'Player'}</div></div><div style="text-align:right"><div class="market-price">${money(x.price)} SH</div><button class="primary" style="width:auto;margin-top:7px" onclick="buyListing(${x.id})">КУПИТЬ</button></div></div></div>`).join(''):'<div class="card empty">По этому запросу объявлений нет.</div>'}
function renderMyListings(){if(!marketData)return;$('myListings').innerHTML=marketData.own?.length?marketData.own.map(x=>`<div class="market-card"><div class="row"><div><b>${x.emoji} ${x.item_name}</b><div class="market-meta">${x.rarity} · ×${x.quantity}</div></div><div style="text-align:right"><div class="market-price">${money(x.price)} SH</div><button class="ghost" style="margin-top:7px" onclick="cancelListing(${x.id})">СНЯТЬ</button></div></div></div>`).join(''):'<div class="card empty">У тебя пока нет объявлений.</div>'}
async function buyListing(id){try{const j=await api('/api/market/buy',{method:'POST',body:JSON.stringify({listing_id:id})});toast(`🛒 Куплено за ${money(j.price)} SH`);await load();await loadMarket()}catch(e){toast(e.reason==='money'?`Не хватает ${money(e.need)} SH`:e.reason==='self'?'Нельзя купить свой предмет':'Объявление уже недоступно')}}
async function cancelListing(id){try{await api('/api/market/cancel',{method:'POST',body:JSON.stringify({listing_id:id})});toast('Объявление снято');await loadMarket()}catch(e){toast('Не удалось снять объявление')}}
async function sellItem(name){const price=prompt(`Цена продажи для ${name}:`);if(!price)return;try{await api('/api/market/sell',{method:'POST',body:JSON.stringify({item:name,price:Number(price),quantity:1})});toast('🏪 Предмет выставлен на рынок');await loadMarket();await loadInventory()}catch(e){toast(e.reason==='item'?'Предмет недоступен':e.reason==='listed'?'Такое количество уже выставлено':'Неверная цена')}}
async function loadCollections(){try{const j=await api('/api/collections');$('collections').innerHTML=j.items.map(c=>`<div class="collection-card ${c.complete?'collection-complete':''}"><div class="row"><div><b>${c.name}</b><div class="muted">Собрано ${c.owned} / ${c.total}</div></div><span class="pill">${c.complete?'COMPLETE':'PROGRESS'}</span></div><div class="progress"><i style="width:${c.owned/c.total*100}%"></i></div><div class="collection-items">${c.items.map(x=>`<span class="collection-item ${x.quantity?'owned':''}">${x.quantity?'✓':'○'} ${x.name}${x.quantity>1?' ×'+x.quantity:''}</span>`).join('')}</div></div>`).join('')}catch(e){toast('Не удалось загрузить коллекции')}}
async function loadRating(){try{const j=await api('/api/leaderboard');$('leaders').innerHTML=j.items.map((x,i)=>`<div class="leader row"><div><b>${i+1}. ${x.first_name||'Player'}</b><div class="muted">Уровень ${x.level} · ${x.packs_opened} кейсов · ${money(x.xp)} XP</div></div><span class="pill">${money(x.balance)} SH</span></div>`).join('')}catch(e){toast('Не удалось загрузить рейтинг')}}
async function loadProfile(){try{const s=data.stats;$('profileGrid').innerHTML=`<div class="card stat"><div class="muted">Уровень</div><b>${s.level}</b></div><div class="card stat"><div class="muted">Серия</div><b>🔥 ${s.streak}</b></div><div class="card stat"><div class="muted">Коллекция</div><b>${s.unique}</b></div><div class="card stat"><div class="muted">Стоимость</div><b>${money(s.inventory_value)} SH</b></div>`;const j=await api('/api/achievements');$('ach').innerHTML=j.items.length?j.items.map(x=>`<div class="achievement"><div class="row"><b>🏆 ${x.title}</b><span class="pill">+${money(x.reward)} SH</span></div></div>`).join(''):'<div class="card empty">Пока нет достижений.</div>'}catch(e){toast('Не удалось загрузить профиль')}}
if(window.Telegram?.WebApp){Telegram.WebApp.ready();Telegram.WebApp.expand();}load();
